# Generated by Django 5.2.3 on 2025-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app_app', '0001_initial'),  # Make sure this is indented properly
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
