# Generated by Django 5.2.3 on 2025-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
