# Generated by Django 5.2.3 on 2025-06-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_add_userdevice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='safe_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breach_alerts', to='api.safezone'),
        ),
        migrations.AddField(
            model_name='safezone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
