# Generated by Django 5.2.3 on 2025-06-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_is_active_to_safezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="e.g., 'School Run', 'Visit to Park'", max_length=100)),
                ('start_location_name', models.CharField(blank=True, max_length=150, null=True)),
                ('start_latitude_approx', models.FloatField(blank=True, null=True)),
                ('start_longitude_approx', models.FloatField(blank=True, null=True)),
                ('end_location_name', models.CharField(blank=True, max_length=150, null=True)),
                ('end_latitude_approx', models.FloatField(blank=True, null=True)),
                ('end_longitude_approx', models.FloatField(blank=True, null=True)),
                ('typical_days_of_week', models.CharField(blank=True, help_text='Comma-separated days (0=Mon, 6=Sun)', max_length=15, null=True)),
                ('typical_time_window_start_min', models.TimeField(blank=True, help_text='Earliest typical start time', null=True)),
                ('typical_time_window_start_max', models.TimeField(blank=True, help_text='Latest typical start time', null=True)),
                ('route_path_approximation_json', models.JSONField(blank=True, help_text='JSON list of [lat, lon] waypoints', null=True)),
                ('last_calculated_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in this learned routine (0.0 to 1.0)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this routine currently considered valid?')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_routines', to='api.child')),
            ],
            options={
                'ordering': ['child', '-confidence_score', '-last_calculated_at'],
            },
        ),
    ]
