# Generated by Django 5.2.3 on 2025-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app_app', '0005_add_learnedroutine_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Is the child's profile/tracking active?"),
        ),
    ]
