# Generated by Django 5.2.3 on 2025-06-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app._app', '0007_add_contextual_weather_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('SOS', 'SOS Panic'), ('LEFT_ZONE', 'Left Safe Zone'), ('ENTERED_ZONE', 'Entered Safe Zone'), ('LOW_BATTERY', 'Low Battery'), ('UNUSUAL_ROUTE', 'Unusual Route Detected'), ('CONTEXTUAL_WEATHER', 'Contextual Weather Alert'), ('CHECK_IN', 'Child Check-In')], max_length=20),
        ),
    ]
