# Generated by Django 5.2.3 on 2025-06-16 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app._app', '0008_add_checkin_alert_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='proxy_user',
            field=models.OneToOneField(blank=True, help_text='Proxy User account for this child for messaging purposes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_child_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
