# Generated by Django 5.2.3 on 2025-06-16 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app._app', '0009_add_proxy_user_to_child'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveEtaShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('calculated_eta', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='eta_shares_received', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_shares_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Active ETA Share',
                'verbose_name_plural': 'Active ETA Shares',
                'ordering': ['-updated_at'],
            },
        ),
    ]
