# Generated by Django 5.0.6 on 2025-06-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_add_active_eta_share_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='last_seen',
            new_name='last_seen_at',
        ),
    ]
